### ISSUE TITLE
Not loading on Linux

### ISSUE THREAD

**Issue by Dalayeth** [LVH-IT/ValheimMods#1]
As of 0.2.0.0 the plugin refuses to load on my Linux dedicated server. 

```
[Message:   BepInEx] BepInEx 5.4.6.0 - valheim_server
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Linux
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2019.4.20f1
[Info   :   BepInEx] Detected Unity version: v2019.4.20f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 13 plugins to load
[Info   :   BepInEx] 13 plugins to load
[Warning:   BepInEx] Skipping [Use Equipment in Water 0.2.0.0] because of process filters (valheim.exe)
[Warning:   BepInEx] Skipping [Use Equipment in Water 0.2.0.0] because of process filters (valheim.exe)
```

Doesn't even get to the point that it makes a config just first thing it refuses to load. Thought it might be "[BepInProcess("valheim.exe")" but it was working in earlier versions. If you need the name of the dedicated server file on Linux it is "valheim_server.x86_64".

**Comment by ElTheLedge** [comment]
Installing this mod on a server wouldn't work as it is a client-side mod. Every one who wants to use this mod has to install it on their client. I have not yet tested this mod on a linux client though, which is why I restricted the mod to only load with valheim.exe

**Comment by Dalayeth** [comment]
Thank you for responding. I have the mod installed on both the server and the clients. So if it isn't intended to load on the server then it must not be working on the clients. I'll look into this but it might be the same as issue #2 in that case. Thanks again for the quick response.
