### ISSUE TITLE
Latest update not working

### ISSUE THREAD

**Issue by frazierzak** [LVH-IT/ValheimMods#2]
Not sure if it's conflicting with another mod but I can no longer use tools while in the water.

My current mod list:
![image](https://user-images.githubusercontent.com/99009/109364783-8e529300-785d-11eb-92e1-99aa72aba655.png)

Please let me know what information I can provide to help narrow down this issue.

**Comment by ElTheLedge** [comment]
BetterDiscordPresence seems to be incompatible for now. With all the other mods, it works fine for me. I'll look into fixing that issue.
Note that I have also found the following mods to be incompatible for now just so you know:
1. Valheim - SafetyNet
2. Kat Edition
3. ﻿﻿﻿ExpertMode

Thanks for reporting.

**Comment by ElTheLedge** [comment]
The newest update v0.2.1 should fix a lot of incompatibilities. You can try it out and let me know if there are still any problems with the mod.
