### ISSUE TITLE
UseEquipmentInWater: disabled equipment is not available when you *stay* in water, not swim

### ISSUE THREAD

**Issue by rysson** [LVH-IT/ValheimMods#4]
On vanilla you can use items when you stay in water. You can't if you swim.

> This Bepinex mod allows you to use all of your equipment and tools while swimming in water.

It's great idea. Especially when I can set in config what is allowed when you swim.
Problem is when you stay in water, not swim. All disabled equipment is not available when you just **stay** in water. 
How to disable them for swimming, but enable when you stay in water, like in vanilla?

It will be wonderful to get all vanilla behavior plus use some equipment when swim.

**Comment by ElTheLedge** [comment]
I dont really understand what you mean by "staying" in water. Do you mean being stationary? In vanilla, the equipment in both of your hands gets unequipped as soon as you go too deep into the water. It doesn't matter wether you are moving in the water or not. So as far as I can tell, the behaviour of my mod is the same as it is in vanilla.

**Comment by rysson** [comment]
I mean "staying in water" when body is more then half in water in vanilla. I get „wet” debuff but I my stamina is regenerating and I can still use any equipment.
I this same situation I can not use disabled equipment in your mod.

This mod looks very nice, but I expect, that I can use everything like vanilla plus use enabled equipment when swimming (eg. hammer and knife).

EDIT: Example:
![20210314-152442-562x461](https://user-images.githubusercontent.com/5898312/111072118-76277880-84d9-11eb-8798-769af5abe64a.png)

**Comment by ElTheLedge** [comment]
You're right. I've never noticed that, so thanks for pointing it out. It's now fixed in v0.2.2

**Comment by rysson** [comment]
Works like a chram, thank you very match.
It's awesome!
