### ISSUE TITLE
PTB Break

### ISSUE THREAD

**Issue by GracefulUni** [LVH-IT/ValheimMods#7]
Will this mod get an update? the current version breaks with the new PTB

[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Character and name IsSwiming and parameters

[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool Use_Equipment_in_Water.UseEquipmentInWater::patchIsSwim(Boolean& __result, Humanoid __instance, float ___m_swimTimer)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Type type, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Use_Equipment_in_Water.UseEquipmentInWater.Awake () (at <7de0ec78b37340d8a1556af5bde36ac0>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()

**Comment by ElTheLedge** [comment]
This is half fixed right now with the newest version of the mod but for now the config does not work anymore because of some changes in the game code which I need to address
